version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./web/static/uploads:/app/web/static/uploads
      - ./web/static/output:/app/web/static/output
    environment:
      - DEVICE=cpu
